# Generated by Django 2.1.2 on 2018-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('userId', models.BigIntegerField()),
                ('latitude', models.FloatField(default=0.0, max_length=21)),
                ('longitude', models.FloatField(default=0.0, max_length=21)),
                ('area', models.TextField(default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Users Location',
                'db_table': 'users_location',
            },
        ),
    ]
